the_list = [ 
	"gold*something key blah", 
	"gold something bleh"
	"yet another gray*key blah", 
	"gray*key blah", 
	"gah gray*key blah", 
	"gray*key bleh"
	"gray*key blah", 
	"gray*key kabloyee", 
	"gray*key blah", 
	"asdf gray*key blah", 
	"gray*key blah", 
	"gray*key blah", 
	"gray*key blah", 
	"gray*key blah", 
	"gold key alakazam", 
	"blah gray*key blah", 
	"gray*key bleh"
	"yet another gray*key blah", 
	"gray*key blah", 
	"gah gray*key blah", 
	"gray*key bleh"
	"gray*key blah", 
	"gray*key kabloyee", 
	"gray*key blah", 
	"asdf gray*key blah", 
	"gray*key blah", 
	"gray*key blah", 
	"gray*key blah", 
	"gray*key blah", 
		"gray*key blah", 
	"gah gray*key blah", 
	"gray*key bleh"
	"gray*key blah", 
	"gray*key kabloyee", 
	"gray*key blah", 
	"asdf gray*key blah", 
	"gray*key blah", 
	"gray*key blah", 
	"gray*key blah", 
	"gray*key blah", 
	"gold key alakazam", 
	"blah gray*key blah", 
	"gray*key bleh"
	"yet another gray*key blah", 
	"gray*key blah", 
	"gah gray*key blah", 
	"gray*key bleh"
	"gray*key blah", 
	"gray*key kabloyee", 
	"gray*key blah", 
	"asdf gray*key blah", 
	"gray*key blah", 
	"gray*key blah", 
	"gray*key blah", 
	"gray*key blah", 
		"gray*key blah", 
	"gah gray*key blah", 
	"gray*key bleh"
	"gray*key blah", 
	"gray*key kabloyee", 
	"gray*key blah", 
	"asdf gray*key blah", 
	"gray*key blah", 
	"gray*key blah", 
	"gray*key blah", 
	"gray*key blah", 
	"gold key alakazam", 
	"blah gray*key blah", 
	"gray*key bleh"
	"yet another gray*key blah", 
	"gray*key blah", 
	"gah gray*key blah", 
	"gray*key bleh"
	"gray*key blah", 
	"gray*key kabloyee", 
	"gray*key blah", 
	"asdf gray*key blah", 
	"gray*key blah", 
	"gray*key blah", 
	"gray*key blah", 
	"gray*key blah", 
	"gold*key",
	"blah you go it!" 
	"gray*key bleh",
	"blah gray*key blah", 
	"gray*key bleh"
	"yet another gray*key blah", 
	"gray*key blah", 
	"gah gray*key blah", 
	"gray*key bleh"
	"gray*key blah", 
	"gray*key kabloyee", 
	"gray*key blah", 
	"asdf gray*key blah", 
	"gray*key blah", 
	"gray*key blah", 
	"gray*key blah", 
	"gray*key blah", 
	"gold key alakazam", 
		"blah gray*key blah", 
	"gray*key bleh"
	"yet another gray*key blah", 
	"gray*key blah", 
	"gah gray*key blah", 
	"gray*key bleh"
	"gray*key blah", 
	"gray*key kabloyee", 
	"gray*key blah", 
	"asdf gray*key blah", 
	"gray*key blah", 
	"gray*key blah", 
	"gray*key blah", 
	"gray*key blah", 
	"gold key alakazam", 
		"blah gray*key blah", 
	"gray*key bleh"
	"yet another gray*key blah", 
	"gray*key blah", 
	"gah gray*key blah", 
	"gray*key bleh"
	"gray*key blah", 
	"gray*key kabloyee", 
	"gray*key blah", 
	"asdf gray*key blah", 
	"gray*key blah", 
	"gray*key blah", 
	"gray*key blah", 
	"gray*key blah", 
	"gold*something key blah", 
	"gold something bleh"
	"yet another gray*key blah", 
	"gray*key blah", 
	"gah gray*key blah", 
	"gray*key bleh"
	"gray*key blah", 
	"gray*key kabloyee", 
	"gray*key blah", 
	"asdf gray*key blah", 
	"gray*key blah", 
	"gray*key blah", 
	"gray*key blah", 
	"gray*key blah", 
	"gold key alakazam", 
	"blah gray*key blah", 
	"gray*key bleh"
	"yet another gray*key blah", 
	"gray*key blah", 
	"gah gray*key blah", 
	"gray*key bleh"
	"gray*key blah", 
	"gray*key kabloyee", 
	"gray*key blah", 
	"asdf gray*key blah", 
	"gray*key blah", 
	"gray*key blah", 
	"gray*key blah", 
	"gray*key blah", 
		"gray*key blah", 
	"gah gray*key blah", 
	"gray*key bleh"
	"gray*key blah", 
	"gray*key kabloyee", 
	"gray*key blah", 
	"asdf gray*key blah", 
	"gray*key blah", 
	"gray*key blah", 
	"gray*key blah", 
	"gray*key blah", 
	"gold key alakazam", 
	"blah gray*key blah", 
	"gray*key bleh"
	"yet another gray*key blah", 
	"gray*key blah", 
	"gah gray*key blah", 
	"gray*key bleh"
	"gray*key blah", 
	"gray*key kabloyee", 
	"gray*key blah", 
	"asdf gray*key blah", 
	"gray*key blah", 
	"gray*key blah", 
	"gray*key blah", 
	"gray*key blah", 
		"gray*key blah", 
	"gah gray*key blah", 
	"gray*key bleh"
	"gray*key blah", 
	"gray*key kabloyee", 
	"gray*key blah", 
	"asdf gray*key blah", 
	"gray*key blah", 
	"gray*key blah", 
	"gray*key blah", 
	"gray*key blah", 
	"gold key alakazam", 
	"blah gray*key blah", 
	"gray*key bleh"
	"yet another gray*key blah", 
	"gray*key blah", 
	"gah gray*key blah", 
	"gray*key bleh"
	"gray*key blah", 
	"gray*key kabloyee", 
	"gray*key blah", 
	"asdf gray*key blah", 
	"gray*key blah", 
	"gray*key blah", 
	"gray*key blah", 
	"gray*key blah", 
	"gold*key",
	"blah you go it!" 
	"gray*key bleh",
	"blah gray*key blah", 
	"gray*key bleh"
	"yet another gray*key blah", 
	"gray*key blah", 
	"gah gray*key blah", 
	"gray*key bleh"
	"gray*key blah", 
	"gray*key kabloyee", 
	"gray*key blah", 
	"asdf gray*key blah", 
	"gray*key blah", 
	"gray*key blah", 
	"gray*key blah", 
	"gray*key blah", 
	"gold key alakazam", 
		"blah gray*key blah", 
	"gray*key bleh"
	"yet another gray*key blah", 
	"gray*key blah", 
	"gah gray*key blah", 
	"gray*key bleh"
	"gray*key blah", 
	"gray*key kabloyee", 
	"gray*key blah", 
	"asdf gray*key blah", 
	"gray*key blah", 
	"gray*key blah", 
	"gray*key blah", 
	"gray*key blah", 
	"gold key alakazam", 
		"blah gray*key blah", 
	"gray*key bleh"
	"yet another gray*key blah", 
	"gray*key blah", 
	"gah gray*key blah", 
	"gray*key bleh"
	"gray*key blah", 
	"gray*key kabloyee", 
	"gray*key blah", 
	"asdf gray*key blah", 
	"gray*key blah", 
	"gray*key blah", 
	"gray*key blah", 
	"gray*key blah"
	]